language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pylint *.py --rcfile=tests/.pylintrc
  - pylint src/ --rcfile=tests/.pylintrc
  - pytest tests/
  - docker build -t cdn-dns-controller -f docker/Dockerfile .